<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/milmor/NLP/blob/main/Notebooks/00_Naive_bayes_animals.ipynb">
    <img src="https://www.tensorflow.org/images/colab_logo_32px.png" />
    Run in Google Colab</a>
  </td>
</table>

# Naive Bayes

In [1]:
l = ["Lobos Gatos Lobos Elefantes",
     "Lobos Lobos Caballos",
     "Lobos Elefantes Lobos",
     "Computadora Procesador Lobos"]

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(l)
X_train_counts.toarray()

array([[0, 0, 1, 1, 2, 0],
       [1, 0, 0, 0, 2, 0],
       [0, 0, 1, 0, 2, 0],
       [0, 1, 0, 0, 1, 1]])

In [3]:
count_vect.vocabulary_

{'lobos': 4,
 'gatos': 3,
 'elefantes': 2,
 'caballos': 0,
 'computadora': 1,
 'procesador': 5}

In [4]:
X_test = count_vect.transform(['Lobos Lobos Lobos Computadora Gatos'])
X_test.toarray()

array([[0, 1, 0, 1, 3, 0]])

In [5]:
from sklearn.naive_bayes import MultinomialNB

In [6]:
bayes_pred = MultinomialNB()
bayes_pred.fit(X_train_counts, [0, 0, 0, 1])

MultinomialNB()

In [7]:
bayes_pred.predict(X_test)

array([0])

- Bolsa de palabras

In [8]:
bayes_pred.feature_count_

array([[1., 0., 2., 1., 6., 0.],
       [0., 1., 0., 0., 1., 1.]])

In [9]:
bayes_pred.predict_proba(X_test)

array([[0.87868974, 0.12131026]])

In [10]:
bayes_pred.class_log_prior_

array([-0.28768207, -1.38629436])

In [11]:
import numpy as np

In [12]:
np.log(3 / 4), np.log(1 / 4)

(-0.2876820724517809, -1.3862943611198906)

In [13]:
bayes_pred.feature_log_prob_

array([[-2.07944154, -2.77258872, -1.67397643, -2.07944154, -0.82667857,
        -2.77258872],
       [-2.19722458, -1.5040774 , -2.19722458, -2.19722458, -1.5040774 ,
        -1.5040774 ]])

- Suavizado y probabilidades de cada característica dada la clase

In [14]:
alpha = 1.0
smoothed_fc  = bayes_pred.feature_count_ + alpha
print(smoothed_fc)
smoothed_cc = smoothed_fc.sum(axis=1)
print(smoothed_cc)
np.log(smoothed_fc) - np.log(
            smoothed_cc.reshape(-1, 1)
        )

[[2. 1. 3. 2. 7. 1.]
 [1. 2. 1. 1. 2. 2.]]
[16.  9.]


array([[-2.07944154, -2.77258872, -1.67397643, -2.07944154, -0.82667857,
        -2.77258872],
       [-2.19722458, -1.5040774 , -2.19722458, -2.19722458, -1.5040774 ,
        -1.5040774 ]])