In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' # Disable tensorflow debugging logs
import tensorflow as tf
import matplotlib.pyplot as plt

## Introducción a tensores

- Tensor

In [2]:
tensor = tf.constant(4)
tensor

<tf.Tensor: shape=(), dtype=int32, numpy=4>

- Vector

In [3]:
tensor = tf.constant([3, 4, 5])
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 5], dtype=int32)>

- Obtener dimensión de tensor con __shape__

In [4]:
tensor.shape

TensorShape([3])

- Tensor de 2 dimensiones

In [5]:
tensor = tf.constant([[3, 4, 5], [3, 4, 5]])
tensor, tensor.shape

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 4, 5],
        [3, 4, 5]], dtype=int32)>,
 TensorShape([2, 3]))

### Operaciones de tensores

In [6]:
tensor = tf.constant([[3, 4], [3, 4]])

In [7]:
tensor + tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 8],
       [6, 8]], dtype=int32)>

In [8]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 16],
       [ 9, 16]], dtype=int32)>

- Multiplicación de matrices con __@__

In [9]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 28],
       [21, 28]], dtype=int32)>

### Métodos de tensores

- Inicialización en ceros. Pasar como argumento la dimensión del tensor

In [10]:
tensor = tf.zeros([3, 3, 9])
tensor.shape

TensorShape([3, 3, 9])

- Método __reshape__

In [11]:
tf.reshape(tensor, [9, 9])

<tf.Tensor: shape=(9, 9), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

- Cast de tensores

In [12]:
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: shape=(3, 3, 9), dtype=uint8, numpy=
array([[[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=uint8)>

- Método __range__

In [13]:
tf.range(4, 8)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 6, 7], dtype=int32)>

### Cadenas en tensores

In [14]:
tf.constant(['Hola como estas'])

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'Hola como estas'], dtype=object)>

- Listas de cadenas

In [15]:
string = tf.constant(['Hola como estas',
                      'Bien y tu?',
                      'Ola k ase?'])

string[0], string[2]

(<tf.Tensor: shape=(), dtype=string, numpy=b'Hola como estas'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'Ola k ase?'>)

- Ejercicio: Crear un tensor de $3 \times 3 \times 2 \times 1$