In [1]:
# The MIT License (MIT) Copyright (c) 2025 Emilio Morales
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or
# substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
# OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/milmor/NLP/blob/main/Notebooks/21_RAG.ipynb">
    <img src="https://www.tensorflow.org/images/colab_logo_32px.png" />
    Run in Google Colab</a>
  </td>
</table>

# RAG

- Game of thrones book: https://www.kaggle.com/datasets/khulasasndh/game-of-thrones-books
- Harry Potter book: https://www.kaggle.com/datasets/gulsahdemiryurek/harry-potter-dataset

In [2]:
!pip install torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0
!pip install transformers==4.55.2 vllm==0.11.0
!pip install faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.9/887.9 MB 1.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 41.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 28.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.4/322.4 MB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 MB 7.8 MB/s eta 0:00:00
  Attempting uninstall: triton
    Found existing installation: triton 3.6.0
    Uninstalling triton-3.6.0:
      Successfully uninstalled triton-3.6.0
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.27.5
    Uninstalling nvidia-nccl-cu12-2.27.5:
      Successfully uninstalled nvidia-nccl-cu12-2.27.5
  Attempting uninstall: torch
    Found existing installation: torch 2.10.0+cu128
    Uninstalling torch-2.10.0+cu128:
      Successfully uninstalled torch-2.10.0+cu128
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.25.0+cu

In [2]:
!pip uninstall -y torchcodec

Found existing installation: torchcodec 0.10.0+cu128
Uninstalling torchcodec-0.10.0+cu128:
  Successfully uninstalled torchcodec-0.10.0+cu128


In [1]:
import torch
import sentence_transformers
import vllm

torch.__version__, sentence_transformers.__version__, vllm.__version__

('2.8.0+cu128', '5.4.1', '0.11.0')

In [2]:
from vllm import LLM, SamplingParams
from datasets import Dataset

INFO 05-09 03:33:43 [__init__.py:216] Automatically detected platform cuda.


In [3]:
def chunk_text(text, chunk_size):
    """Splits text into chunks of a specified size."""
    words = text.split()
    chunks = [' '.join(words[i:i + chunk_size]) for i in range(0, len(words), chunk_size)]
    return chunks

with open('./Book1.txt', 'r', encoding='utf-8') as f:
    book_text = f.read()

chunk_size = 500  # You can adjust the chunk size as needed
book_chunks = chunk_text(book_text, chunk_size)

print(f"Number of chunks created: {len(book_chunks)}")
print(f"First chunk: {book_chunks[0][:200]}...") # Print the first 200 characters of the first chunk

Number of chunks created: 167
First chunk: / THE BOY WHO LIVED Mr. and Mrs. Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much. They were the last people you’d expect to be involved in...


## Vector Database

In [4]:
from sentence_transformers import SentenceTransformer
from sentence_transformers.util import cos_sim

In [5]:
model = SentenceTransformer(
    "all-MiniLM-L6-v2" # Using a small model
)

# The actual max sequence length for this model is 512
model.max_seq_length = 512

embeddings = model.encode([
    'How is the weather today?',
    'What is the current weather like today?'
])
print(cos_sim(embeddings[0], embeddings[1]))

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tensor([[0.8852]])


In [6]:
embeddings[0].shape

(384,)

In [7]:
embeddings = model.encode([
    'How is the weather today?',
    'What is the current weather like today?'
])
print(cos_sim(embeddings[0], embeddings[1]))

tensor([[0.8852]])


In [8]:
embeddings = model.encode([
    'How is the weather today?',
    "What's the name of your dog"
])

print(cos_sim(embeddings[0], embeddings[1]))

tensor([[0.0808]])


In [9]:
my_dict = {
    "id": list(range(len(book_chunks))),
    "text": book_chunks}

book = Dataset.from_dict(my_dict)
book

Dataset({
    features: ['id', 'text'],
    num_rows: 167
})

In [10]:
def embed(batch):
  # Explicitly truncate text to the model's max sequence length
  truncated_texts = [text[:model.max_seq_length] for text in batch["text"]]
  info = model.encode(truncated_texts)
  return {"embeddings": info}

dataset = book.map(embed, batched=True)

Map:   0%|          | 0/167 [00:00<?, ? examples/s]

In [11]:
dataset

Dataset({
    features: ['id', 'text', 'embeddings'],
    num_rows: 167
})

In [12]:
data = dataset.add_faiss_index(column="embeddings")

  0%|          | 0/1 [00:00<?, ?it/s]

In [13]:
def search(query, k):
  emb_query = model.encode([query])
  return data.get_nearest_examples("embeddings", emb_query, k=k)

In [14]:
scores, result = search("Why does Voldemort want the stone?", 3)
result['text']

['Stone, but rest assured, no one can possibly steal it, it’s too well protected.” “But Professor — ” Page | 300 Harry Potter and the Philosophers Stone - J.K. Rowling “Potter, I know what I’m talking about,” she said shortly. She bent down and gathered up the fallen books. “I suggest you all go back outside and enjoy the sunshine.” But they didn’t. “It’s tonight,” said Harry, once he was sure Professor McGonagall was out of earshot. “Snape’s going through the trapdoor tonight. He’s found out everything he needs, and now he’s got Dumbledore out of the way. He sent that note, I bet the Ministry of Magic will get a real shock when Dumbledore turns up.” “But what can we — ” Hermione gasped. Harry and Ron wheeled round. Snape was standing there. “Good afternoon,” he said smoothly. They stared at him. “You shouldn’t be inside on a day like this,” he said, with an odd, twisted smile. “We were — ” Harry began, without any idea what he was going to say. “You want to be more careful,” said Snap

## LLM

In [15]:
from transformers import AutoTokenizer

#model_id = "neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8-dynamic"
model_id = "neuralmagic/Meta-Llama-3.1-8B-Instruct-quantized.w4a16"

number_gpus = 1
tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=True)
max_model_len = 8192

sampling_params = SamplingParams(temperature=0.6, top_p=0.9, max_tokens=256)
llm = LLM(model=model_id, tokenizer=model_id, tensor_parallel_size=number_gpus, max_model_len=max_model_len)

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

INFO 05-09 03:33:55 [utils.py:233] non-default args: {'tokenizer': 'neuralmagic/Meta-Llama-3.1-8B-Instruct-quantized.w4a16', 'max_model_len': 8192, 'disable_log_stats': True, 'model': 'neuralmagic/Meta-Llama-3.1-8B-Instruct-quantized.w4a16'}


config.json: 0.00B [00:00, ?B/s]

INFO 05-09 03:34:24 [model.py:547] Resolved architecture: LlamaForCausalLM
INFO 05-09 03:34:24 [model.py:1510] Using max model len 8192
INFO 05-09 03:34:24 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=8192.
WARNING 05-09 03:34:27 [__init__.py:3036] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
INFO 05-09 03:42:44 [llm.py:306] Supported_tasks: ['generate']


In [16]:
def format_prompt_chatbot(prompt, docs, k):
  context = "\n".join(docs['text'][:k])
  full_prompt = f"Question: {prompt} \nContext: {context}"
  return {"role": "user", "content": full_prompt}

def generate(message):
  prompts = tokenizer.apply_chat_template(message, tokenize=False, add_generation_prompt=True)
  outputs = llm.generate(prompts, sampling_params)
  return outputs[0].outputs[0].text

def rag_llama(prompt, k=3):
  scores, docs = search(prompt, k)

  user_message = format_prompt_chatbot(prompt, docs, k)
  system_message = {"role": "system", "content": "You are a helpful assistant for answering questions. "
  " You are given the extracted parts of a long document. Provide a conversational answer. \n"}
  message = [system_message, user_message]

  return generate(message)

In [17]:
output = rag_llama("Why does Voldemort want the stone?")
print(output)

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Voldemort wants the Sorcerer's Stone to achieve immortality. He plans to use the Stone to create the Elixir of Life, which will give him a physical body and allow him to be a powerful wizard without relying on possessing other people's bodies. The Elixir of Life is a powerful potion that can grant eternal life, and Voldemort believes that with it, he will be able to achieve his ultimate goal of immortality.


In [18]:
output = rag_llama("Why does Voldemort want the stone?")
print(output)

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Voldemort wants the Sorcerer's Stone because he plans to use it to create a body of his own, allowing him to achieve his ultimate goal of immortality. He has been using Quirrell as a host, but the Stone is necessary for him to create a permanent body and gain the strength to achieve his dark ambitions.


In [19]:
output = rag_llama("How did Harry and Ron become friends on the train?")
print(output)

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Harry and Ron became friends on the train when Ron saw Harry being addressed by the Hogwarts staff as "Harry Potter" and learned that he was the boy who was going to play Quidditch for Gryffindor house. Ron was amazed and impressed by this news, and they started talking. Ron introduced himself to Harry, and they began to chat about Quidditch and the upcoming season.
